# permissions for end users to view avalanchegoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: avalanchego-viewer-role
rules:
- apiGroups:
  - chain.djtx.network
  resources:
  - avalanchegoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chain.djtx.network
  resources:
  - avalanchegoes/status
  verbs:
  - get
